server:
  port: 8085

spring:
  application:
    name: post-service
  webflux:
    base-path: /api

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/forum-kma-db?timeZone=Asia/Ho_Chi_Minh
    username: postgres
    password: 123456

  data:
    redis:
      host: localhost
      port: 6060
      password:
      timeout: 6000ms

  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:7092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="123456";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: post-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
